INSERT INTO mail (id_persona,mail,tipo)
VALUES
  (484,'diam.dictum.sapien@nisl.co.uk','EMPRESARIAL'),
  (233,'magna.sed@massalobortis.edu','EMPRESARIAL'),
  (483,'convallis@natoquepenatibus.org','PERSONAL'),
  (358,'dictum.phasellus@varius.co.uk','INSTITUCIONAL'),
  (409,'nec@portaelit.org','EMPRESARIAL'),
  (227,'suspendisse@est.edu','PERSONAL'),
  (170,'commodo@tincidunt.co.uk','INSTITUCIONAL'),
  (476,'mus.proin@donectempor.org','INSTITUCIONAL'),
  (197,'velit@non.com','PERSONAL'),
  (179,'at.libero@vulputatedui.org','INSTITUCIONAL');
INSERT INTO mail (id_persona,mail,tipo)
VALUES
  (414,'nam.consequat.dolor@nullaintegervulputate.com','EMPRESARIAL'),
  (289,'est.nunc@augueeutellus.net','EMPRESARIAL'),
  (364,'non.sapien.molestie@nulla.com','INSTITUCIONAL'),
  (158,'porttitor@ipsumprimis.net','PERSONAL'),
  (419,'id.magna.et@bibendumsed.ca','EMPRESARIAL'),
  (270,'mattis@etarcu.co.uk','INSTITUCIONAL'),
  (287,'natoque@purusmaurisa.org','EMPRESARIAL'),
  (282,'integer@ametconsectetueradipiscing.ca','INSTITUCIONAL'),
  (188,'donec.tempus@sociisnatoquepenatibus.net','INSTITUCIONAL'),
  (403,'et.commodo.at@aliquam.net','INSTITUCIONAL');
INSERT INTO mail (id_persona,mail,tipo)
VALUES
  (112,'libero.est@et.co.uk','PERSONAL'),
  (578,'malesuada.malesuada.integer@naminterdum.co.uk','INSTITUCIONAL'),
  (390,'egestas.duis@namnulla.edu','INSTITUCIONAL'),
  (424,'convallis.erat.eget@egestashendrerit.edu','EMPRESARIAL'),
  (395,'ut@hendreritnequein.co.uk','EMPRESARIAL'),
  (129,'sem.vitae.aliquam@ipsumprimis.co.uk','INSTITUCIONAL'),
  (508,'ante.vivamus.non@integereu.ca','INSTITUCIONAL'),
  (442,'quis.accumsan.convallis@mollisvitae.co.uk','EMPRESARIAL'),
  (225,'vivamus.molestie@faucibusleoin.ca','EMPRESARIAL'),
  (285,'interdum.ligula@dictum.edu','PERSONAL');
INSERT INTO mail (id_persona,mail,tipo)
VALUES
  (215,'felis@rutrumlorem.org','EMPRESARIAL'),
  (217,'nec.metus.facilisis@aeneangravida.org','INSTITUCIONAL'),
  (383,'senectus.et@enim.net','PERSONAL'),
  (481,'duis.mi.enim@ametfaucibus.com','INSTITUCIONAL'),
  (321,'enim.sed.nulla@ligulanullam.com','INSTITUCIONAL'),
  (333,'facilisis.facilisis.magna@anteipsumprimis.co.uk','PERSONAL'),
  (348,'egestas.sed@dapibusid.ca','PERSONAL'),
  (395,'sagittis.felis@ultrices.ca','PERSONAL'),
  (513,'ut.quam@vehicula.ca','EMPRESARIAL'),
  (305,'cursus.integer.mollis@aliquetnec.org','PERSONAL');
INSERT INTO mail (id_persona,mail,tipo)
VALUES
  (214,'lorem@noncursusnon.net','EMPRESARIAL'),
  (178,'ultricies.sem.magna@nullaintegervulputate.org','INSTITUCIONAL'),
  (270,'semper.auctor@inmi.net','EMPRESARIAL'),
  (596,'etiam.laoreet@utmolestiein.ca','INSTITUCIONAL'),
  (371,'risus.donec@liberoatauctor.co.uk','PERSONAL'),
  (191,'mauris@aliquameu.net','EMPRESARIAL'),
  (275,'mattis.ornare@auctornon.org','INSTITUCIONAL'),
  (579,'sed.pharetra@tempusnon.ca','PERSONAL'),
  (193,'sed.turpis@semper.net','INSTITUCIONAL'),
  (300,'nullam.vitae.diam@sit.org','EMPRESARIAL');
INSERT INTO mail (id_persona,mail,tipo)
VALUES
  (477,'tempor.diam@urnanec.edu','EMPRESARIAL'),
  (307,'ac.feugiat.non@magnisdis.edu','EMPRESARIAL'),
  (481,'adipiscing.mauris@amagnalorem.org','PERSONAL'),
  (246,'donec.tincidunt.donec@magnanecquam.com','INSTITUCIONAL'),
  (469,'arcu@ametmetusaliquam.edu','INSTITUCIONAL'),
  (440,'urna.nunc@ac.edu','INSTITUCIONAL'),
  (119,'interdum.sed@nulla.co.uk','PERSONAL'),
  (296,'mus.aenean@risusduisa.co.uk','INSTITUCIONAL'),
  (115,'tempus.non.lacinia@arcuvestibulum.net','PERSONAL'),
  (119,'et.euismod@at.ca','EMPRESARIAL');
INSERT INTO mail (id_persona,mail,tipo)
VALUES
  (570,'pretium.neque@luctus.com','INSTITUCIONAL'),
  (525,'lacus.cras.interdum@vulputatenisi.com','EMPRESARIAL'),
  (569,'tincidunt.adipiscing@aliquet.org','PERSONAL'),
  (234,'lobortis@aodio.net','EMPRESARIAL'),
  (598,'sed.dui@ametdiam.net','PERSONAL'),
  (409,'in.nec.orci@eudui.net','PERSONAL'),
  (516,'quis@id.org','EMPRESARIAL'),
  (546,'amet@sempernam.com','INSTITUCIONAL'),
  (257,'euismod.mauris.eu@pharetraquisqueac.net','PERSONAL'),
  (319,'fames.ac@eratnonummy.co.uk','INSTITUCIONAL');
INSERT INTO mail (id_persona,mail,tipo)
VALUES
  (111,'enim.suspendisse@elementum.net','INSTITUCIONAL'),
  (432,'a.odio.semper@dolortempusnon.ca','INSTITUCIONAL'),
  (149,'eget.ipsum@faucibuslectus.co.uk','EMPRESARIAL'),
  (326,'eu.neque.pellentesque@est.org','PERSONAL'),
  (513,'ut.ipsum.ac@vestibulumnec.net','EMPRESARIAL'),
  (563,'ut.mi.duis@elementumlorem.com','EMPRESARIAL'),
  (579,'mus.proin.vel@vitaeerat.ca','PERSONAL'),
  (577,'elit.pharetra@felisnullatempor.org','INSTITUCIONAL'),
  (231,'laoreet.lectus.quis@a.edu','PERSONAL'),
  (308,'integer.eu@sitamet.com','EMPRESARIAL');
INSERT INTO mail (id_persona,mail,tipo)
VALUES
  (331,'orci@nullainteger.net','INSTITUCIONAL'),
  (449,'donec.fringilla@euodiotristique.ca','EMPRESARIAL'),
  (284,'nulla@curabitur.ca','PERSONAL'),
  (118,'fames@lacus.ca','EMPRESARIAL'),
  (374,'dui.cum@sagittisfelisdonec.edu','INSTITUCIONAL'),
  (259,'tincidunt.congue.turpis@nullam.com','PERSONAL'),
  (554,'porttitor.interdum.sed@magnacras.net','INSTITUCIONAL'),
  (287,'et.arcu@mollis.edu','INSTITUCIONAL'),
  (454,'augue.sed@donecsollicitudin.org','EMPRESARIAL'),
  (215,'gravida@nullam.com','PERSONAL');
INSERT INTO mail (id_persona,mail,tipo)
VALUES
  (253,'elit.elit@antelectusconvallis.com','INSTITUCIONAL'),
  (453,'sagittis.lobortis@interdumcurabiturdictum.ca','INSTITUCIONAL'),
  (244,'aliquam@consequat.ca','EMPRESARIAL'),
  (581,'mi.tempor@blanditnam.com','PERSONAL'),
  (161,'maecenas.ornare@quisquenonummyipsum.co.uk','INSTITUCIONAL'),
  (505,'ligula.nullam@integer.com','EMPRESARIAL'),
  (586,'at.libero.morbi@pedesuspendisse.co.uk','PERSONAL'),
  (363,'elit.elit.fermentum@euismodest.co.uk','INSTITUCIONAL'),
  (532,'metus@nuncnullavulputate.org','INSTITUCIONAL'),
  (443,'ut.semper@pedeultrices.co.uk','EMPRESARIAL');
INSERT INTO mail (id_persona,mail,tipo)
VALUES
  (258,'faucibus.ut@enimmi.ca','INSTITUCIONAL'),
  (432,'libero.mauris.aliquam@quis.com','EMPRESARIAL'),
  (241,'facilisis.eget.ipsum@sedet.net','INSTITUCIONAL'),
  (571,'turpis.in@integeraliquamadipiscing.com','INSTITUCIONAL'),
  (402,'massa.mauris@magna.co.uk','EMPRESARIAL'),
  (564,'cursus.luctus@senectuset.net','PERSONAL'),
  (468,'tincidunt.pede@dapibus.com','INSTITUCIONAL'),
  (280,'eu.dui.cum@orcidonec.org','INSTITUCIONAL'),
  (535,'donec.dignissim@nonmassa.edu','INSTITUCIONAL'),
  (127,'convallis.dolor@etmagnis.net','INSTITUCIONAL');
INSERT INTO mail (id_persona,mail,tipo)
VALUES
  (476,'fames@iaculisodionam.org','EMPRESARIAL'),
  (123,'integer.tincidunt@mauris.org','INSTITUCIONAL'),
  (477,'nunc.nulla@sednulla.com','EMPRESARIAL'),
  (114,'vestibulum.ante@hendreritneque.ca','PERSONAL'),
  (185,'tincidunt.donec@sociis.net','EMPRESARIAL'),
  (328,'suspendisse.tristique.neque@primisin.com','EMPRESARIAL'),
  (165,'lorem@orciutsemper.org','INSTITUCIONAL'),
  (127,'dis.parturient@in.co.uk','PERSONAL'),
  (549,'nibh.dolor@euaugue.net','PERSONAL'),
  (378,'sit.amet@atiaculis.net','PERSONAL');
INSERT INTO mail (id_persona,mail,tipo)
VALUES
  (289,'velit.egestas.lacinia@ipsumsodales.com','EMPRESARIAL'),
  (291,'enim.suspendisse.aliquet@sollicitudincommodoipsum.org','INSTITUCIONAL'),
  (239,'justo.nec@nequeetnunc.edu','PERSONAL'),
  (237,'fames.ac@turpisvitae.net','EMPRESARIAL'),
  (230,'dui@augueidante.net','PERSONAL'),
  (119,'consequat.dolor@consectetuerrhoncus.ca','EMPRESARIAL'),
  (329,'risus@porta.net','INSTITUCIONAL'),
  (472,'integer.mollis.integer@phasellusdapibus.edu','PERSONAL'),
  (204,'aliquam.vulputate@felisegetvarius.com','PERSONAL'),
  (495,'dictum@orciin.edu','PERSONAL');
INSERT INTO mail (id_persona,mail,tipo)
VALUES
  (300,'sem.magna@arcuvivamus.edu','EMPRESARIAL'),
  (286,'sociis.natoque@faucibusorci.co.uk','INSTITUCIONAL'),
  (475,'etiam@scelerisquemollis.ca','INSTITUCIONAL'),
  (170,'neque.sed@metusin.ca','PERSONAL'),
  (478,'phasellus@curabitur.co.uk','INSTITUCIONAL'),
  (264,'condimentum.eget@eliteratvitae.net','INSTITUCIONAL'),
  (178,'hendrerit.neque@arcused.org','EMPRESARIAL'),
  (429,'erat.vel@cum.org','PERSONAL'),
  (520,'tincidunt.nunc.ac@ligulaaeneangravida.com','INSTITUCIONAL'),
  (343,'et.malesuada@vitaeodio.org','EMPRESARIAL');
INSERT INTO mail (id_persona,mail,tipo)
VALUES
  (436,'a.magna@vel.edu','INSTITUCIONAL'),
  (203,'elementum.dui@fringillaest.org','INSTITUCIONAL'),
  (181,'nonummy.ultricies.ornare@blanditenim.ca','EMPRESARIAL'),
  (234,'aliquam.nec@temporarcu.org','EMPRESARIAL'),
  (304,'suspendisse@quampellentesque.co.uk','EMPRESARIAL'),
  (172,'nec.tellus@mattisintegereu.ca','PERSONAL'),
  (351,'id.ante.dictum@amet.com','PERSONAL'),
  (587,'feugiat.sed.nec@sagittisfelisdonec.net','PERSONAL'),
  (338,'elementum.dui@lectusnullam.com','EMPRESARIAL'),
  (351,'posuere.cubilia@cursuspurus.co.uk','PERSONAL');
INSERT INTO mail (id_persona,mail,tipo)
VALUES
  (372,'eget@molestiesed.org','EMPRESARIAL'),
  (144,'libero@nullasemper.org','INSTITUCIONAL'),
  (579,'odio.phasellus@aliquam.ca','EMPRESARIAL'),
  (112,'auctor.odio@ridiculus.co.uk','PERSONAL'),
  (531,'euismod.mauris.eu@viverradonec.net','EMPRESARIAL'),
  (398,'mauris.nulla@tristiquepellentesque.org','PERSONAL'),
  (566,'tortor.at@aliquetlobortisnisi.com','INSTITUCIONAL'),
  (192,'aenean.massa.integer@maurissuspendisse.co.uk','INSTITUCIONAL'),
  (412,'nec.leo@metusurna.ca','EMPRESARIAL'),
  (213,'scelerisque.lorem@convallisantelectus.co.uk','PERSONAL');
INSERT INTO mail (id_persona,mail,tipo)
VALUES
  (258,'pede@pharetraut.com','INSTITUCIONAL'),
  (328,'erat@iaculisaliquet.ca','INSTITUCIONAL'),
  (555,'aliquam.adipiscing.lacus@urnasuscipitnonummy.org','INSTITUCIONAL'),
  (374,'risus.a@tellusfaucibusleo.com','EMPRESARIAL'),
  (413,'aliquet@suspendissesed.edu','PERSONAL'),
  (434,'vulputate.dui.nec@magnaetipsum.net','PERSONAL'),
  (377,'egestas.rhoncus@id.co.uk','EMPRESARIAL'),
  (235,'imperdiet.nec.leo@leoelementumsem.com','EMPRESARIAL'),
  (143,'tempor.est.ac@ligulaaeneangravida.net','PERSONAL'),
  (387,'tempor@facilisisvitaeorci.com','EMPRESARIAL');
INSERT INTO mail (id_persona,mail,tipo)
VALUES
  (430,'euismod@atpedecras.edu','EMPRESARIAL'),
  (261,'vivamus.nibh.dolor@euodio.edu','INSTITUCIONAL'),
  (122,'quis.arcu@phaselluslibero.org','EMPRESARIAL'),
  (263,'arcu.aliquam@sapiennunc.co.uk','INSTITUCIONAL'),
  (587,'lorem.ipsum.dolor@orcilobortis.co.uk','PERSONAL'),
  (235,'vulputate.lacus@arcuvelquam.org','PERSONAL'),
  (351,'in@erosturpis.ca','INSTITUCIONAL'),
  (245,'egestas@turpisnulla.edu','INSTITUCIONAL'),
  (516,'dolor@sapien.edu','EMPRESARIAL'),
  (231,'ipsum@sedmolestie.co.uk','EMPRESARIAL');
INSERT INTO mail (id_persona,mail,tipo)
VALUES
  (375,'duis.dignissim.tempor@fringillapurus.ca','PERSONAL'),
  (554,'posuere.at.velit@antelectusconvallis.org','EMPRESARIAL'),
  (564,'ut.sagittis@antenunc.com','PERSONAL'),
  (545,'est.mauris@sedet.net','INSTITUCIONAL'),
  (318,'sagittis@ultricesvivamus.co.uk','EMPRESARIAL'),
  (271,'eleifend.vitae@incursuset.edu','INSTITUCIONAL'),
  (463,'sed.pede.nec@egestasfusce.net','PERSONAL'),
  (473,'nibh.quisque@maurisut.net','PERSONAL'),
  (461,'et.euismod.et@eudolor.net','INSTITUCIONAL'),
  (217,'eget.massa@cras.net','EMPRESARIAL');
INSERT INTO mail (id_persona,mail,tipo)
VALUES
  (287,'pede@sit.com','EMPRESARIAL'),
  (456,'molestie.sed@pellentesqueutipsum.net','PERSONAL'),
  (421,'nec.cursus@necmaurisblandit.edu','PERSONAL'),
  (381,'augue.malesuada@semegestas.com','INSTITUCIONAL'),
  (463,'dignissim@semperrutrum.co.uk','INSTITUCIONAL'),
  (438,'cursus.nunc@auctormauris.net','EMPRESARIAL'),
  (244,'felis.orci@magnisdis.com','PERSONAL'),
  (257,'elementum.sem@nequetellusimperdiet.com','EMPRESARIAL'),
  (396,'luctus.felis.purus@enim.edu','PERSONAL'),
  (315,'donec.elementum@phasellus.com','EMPRESARIAL');
INSERT INTO mail (id_persona,mail,tipo)
VALUES
  (354,'ut.semper@quisdiam.edu','INSTITUCIONAL'),
  (235,'orci.phasellus@proinsedturpis.co.uk','INSTITUCIONAL'),
  (416,'praesent@urnanecluctus.edu','EMPRESARIAL'),
  (187,'fringilla.ornare@consectetueripsum.org','EMPRESARIAL'),
  (309,'tempus.lorem.fringilla@vestibulumnec.edu','EMPRESARIAL'),
  (481,'sed.libero@euligulaaenean.com','INSTITUCIONAL'),
  (297,'per.inceptos@imperdietnonvestibulum.co.uk','PERSONAL'),
  (454,'facilisis.suspendisse.commodo@tinciduntnunc.ca','PERSONAL'),
  (136,'egestas.hendrerit.neque@semperrutrum.co.uk','EMPRESARIAL'),
  (283,'vestibulum.accumsan@convallisantelectus.edu','INSTITUCIONAL');
INSERT INTO mail (id_persona,mail,tipo)
VALUES
  (437,'neque@vivamusrhoncus.ca','EMPRESARIAL'),
  (475,'id@elit.ca','PERSONAL'),
  (544,'arcu.nunc.mauris@convallisest.net','EMPRESARIAL'),
  (160,'nec@ipsumdonecsollicitudin.edu','INSTITUCIONAL'),
  (177,'vestibulum@quis.com','PERSONAL'),
  (281,'tincidunt@acorci.edu','PERSONAL'),
  (125,'pellentesque.tincidunt@donecfelis.edu','INSTITUCIONAL'),
  (461,'mauris.blandit@lobortisultrices.org','PERSONAL'),
  (563,'in.lorem@pellentesqueseddictum.org','PERSONAL'),
  (483,'nonummy.ut@velitpellentesqueultricies.ca','INSTITUCIONAL');
INSERT INTO mail (id_persona,mail,tipo)
VALUES
  (519,'erat.neque.non@dolordapibus.net','PERSONAL'),
  (318,'phasellus@atiaculisquis.com','INSTITUCIONAL'),
  (291,'praesent.eu@suspendissesagittis.com','PERSONAL'),
  (589,'eleifend.egestas@ligulanullam.net','EMPRESARIAL'),
  (256,'enim.gravida@aenean.ca','EMPRESARIAL'),
  (248,'nisl.elementum.purus@magna.ca','INSTITUCIONAL'),
  (477,'donec.sollicitudin@craspellentesque.edu','PERSONAL'),
  (428,'dignissim.pharetra.nam@dictum.edu','EMPRESARIAL'),
  (419,'leo.elementum@posuere.net','EMPRESARIAL'),
  (351,'leo.in@sedsapiennunc.co.uk','PERSONAL');
INSERT INTO mail (id_persona,mail,tipo)
VALUES
  (301,'erat.etiam.vestibulum@tristiquenequevenenatis.org','INSTITUCIONAL'),
  (127,'nunc.mauris.sapien@tortor.edu','EMPRESARIAL'),
  (326,'et@magnisdis.co.uk','INSTITUCIONAL'),
  (134,'donec.tempus@eget.net','INSTITUCIONAL'),
  (239,'pellentesque.massa.lobortis@velitaliquamnisl.co.uk','INSTITUCIONAL'),
  (413,'justo@nullatincidunt.co.uk','INSTITUCIONAL'),
  (417,'in.nec@ultriciesdignissimlacus.co.uk','EMPRESARIAL'),
  (267,'nulla.tincidunt.neque@accumsan.edu','INSTITUCIONAL'),
  (348,'magna.lorem@velvulputate.co.uk','EMPRESARIAL'),
  (257,'sollicitudin.adipiscing@adipiscinglacus.org','EMPRESARIAL');
INSERT INTO mail (id_persona,mail,tipo)
VALUES
  (424,'vitae.mauris@ornaresagittis.net','EMPRESARIAL'),
  (214,'pellentesque.habitant@felispurus.com','PERSONAL'),
  (440,'consectetuer.rhoncus.nullam@odioapurus.co.uk','INSTITUCIONAL'),
  (500,'at.lacus@duis.ca','PERSONAL'),
  (180,'nunc.mauris@sitamet.ca','INSTITUCIONAL'),
  (215,'neque.et.nunc@sollicitudina.net','PERSONAL'),
  (494,'semper.nam.tempor@vel.com','INSTITUCIONAL'),
  (234,'nunc.id@felispurus.edu','INSTITUCIONAL'),
  (246,'molestie@aeneangravida.net','EMPRESARIAL'),
  (359,'non.ante@urnaconvallis.com','PERSONAL');
INSERT INTO mail (id_persona,mail,tipo)
VALUES
  (316,'amet.diam@est.edu','INSTITUCIONAL'),
  (570,'eu.dui.cum@lacus.net','EMPRESARIAL'),
  (274,'sit.amet@phaselluselit.ca','INSTITUCIONAL'),
  (396,'aliquam@dignissim.edu','PERSONAL'),
  (266,'nam.tempor@fermentumarcuvestibulum.co.uk','EMPRESARIAL'),
  (207,'vitae.diam@aliquameu.ca','INSTITUCIONAL'),
  (419,'ullamcorper.duis@euismodestarcu.org','INSTITUCIONAL'),
  (201,'risus.morbi.metus@dolorfusce.net','EMPRESARIAL'),
  (397,'pellentesque.sed@eu.co.uk','EMPRESARIAL'),
  (302,'eleifend@a.edu','PERSONAL');
INSERT INTO mail (id_persona,mail,tipo)
VALUES
  (284,'ridiculus.mus@ligulanullam.net','INSTITUCIONAL'),
  (197,'enim.consequat.purus@magnacras.ca','EMPRESARIAL'),
  (524,'ipsum.porta@faucibus.ca','INSTITUCIONAL'),
  (393,'sed.congue@dolorsit.org','EMPRESARIAL'),
  (547,'eget.laoreet@turpisnec.edu','INSTITUCIONAL'),
  (230,'adipiscing.elit.aliquam@egestasligula.ca','PERSONAL'),
  (599,'nullam.suscipit@habitantmorbi.ca','INSTITUCIONAL'),
  (450,'rhoncus.proin@duinec.edu','PERSONAL'),
  (600,'porttitor.scelerisque@mienimcondimentum.ca','EMPRESARIAL'),
  (490,'dapibus.id@posuere.ca','PERSONAL');
INSERT INTO mail (id_persona,mail,tipo)
VALUES
  (347,'sed.tortor.integer@cum.org','PERSONAL'),
  (365,'lorem.vehicula@et.co.uk','EMPRESARIAL'),
  (431,'porttitor.interdum.sed@orciluctuset.ca','PERSONAL'),
  (289,'egestas.aliquam.nec@loremfringilla.ca','EMPRESARIAL'),
  (419,'eget.odio@tristiqueac.net','PERSONAL'),
  (366,'nec.urna.et@tacitisociosqu.com','EMPRESARIAL'),
  (195,'dui.suspendisse.ac@praesenteu.org','INSTITUCIONAL'),
  (398,'tristique.senectus@mauris.org','INSTITUCIONAL'),
  (217,'donec.elementum.lorem@justo.org','PERSONAL'),
  (303,'est@senectusetnetus.org','PERSONAL');
INSERT INTO mail (id_persona,mail,tipo)
VALUES
  (507,'elementum.purus.accumsan@nibh.net','EMPRESARIAL'),
  (232,'at@sedet.com','EMPRESARIAL'),
  (292,'odio@laciniavitae.org','INSTITUCIONAL'),
  (259,'ligula.tortor@afelis.org','PERSONAL'),
  (160,'ultrices@iaculis.org','EMPRESARIAL'),
  (483,'at.auctor@sagittisfelisdonec.co.uk','PERSONAL'),
  (457,'libero.donec.consectetuer@lobortis.com','PERSONAL'),
  (427,'non.bibendum@etiamimperdietdictum.co.uk','EMPRESARIAL'),
  (135,'nulla.in@consectetueradipiscingelit.edu','INSTITUCIONAL'),
  (555,'natoque@egetmetusin.co.uk','INSTITUCIONAL');
INSERT INTO mail (id_persona,mail,tipo)
VALUES
  (238,'vel.quam@eget.ca','INSTITUCIONAL'),
  (223,'lorem@ataugue.org','INSTITUCIONAL'),
  (266,'quis.lectus@hendrerit.edu','EMPRESARIAL'),
  (313,'vestibulum.mauris@nec.co.uk','INSTITUCIONAL'),
  (124,'placerat.eget@nonleo.edu','INSTITUCIONAL'),
  (509,'aliquam.adipiscing.lobortis@cum.org','INSTITUCIONAL'),
  (577,'duis.cursus@tellusphasellus.ca','PERSONAL'),
  (371,'vestibulum.ante.ipsum@ac.com','PERSONAL'),
  (395,'arcu.eu@arcusedeu.ca','INSTITUCIONAL'),
  (394,'donec.consectetuer.mauris@inaliquet.net','EMPRESARIAL');
INSERT INTO mail (id_persona,mail,tipo)
VALUES
  (524,'enim.curabitur.massa@adipiscing.com','INSTITUCIONAL'),
  (331,'convallis@curaedonec.com','EMPRESARIAL'),
  (336,'est@lobortis.com','INSTITUCIONAL'),
  (498,'pellentesque.tincidunt.tempus@praesentluctuscurabitur.ca','PERSONAL'),
  (369,'velit.dui@afelis.co.uk','EMPRESARIAL'),
  (488,'bibendum.sed@mus.com','EMPRESARIAL'),
  (590,'eu.nibh@auctor.co.uk','PERSONAL'),
  (567,'hymenaeos.mauris@aeneanegestashendrerit.ca','EMPRESARIAL'),
  (244,'nec.imperdiet@curabiturconsequatlectus.ca','PERSONAL'),
  (345,'sit.amet@sociisnatoque.co.uk','INSTITUCIONAL');
INSERT INTO mail (id_persona,mail,tipo)
VALUES
  (434,'aliquet.libero@egestasligula.net','PERSONAL'),
  (496,'vitae.diam@egetmollis.net','INSTITUCIONAL'),
  (371,'lacus.cras@vulputate.net','INSTITUCIONAL'),
  (562,'massa.integer.vitae@cumsociis.co.uk','INSTITUCIONAL'),
  (121,'eleifend@namnulla.co.uk','PERSONAL'),
  (127,'eu.euismod@iaculisnec.org','INSTITUCIONAL'),
  (554,'aliquam.arcu@crasconvallis.ca','INSTITUCIONAL'),
  (243,'mauris@acrisusmorbi.net','PERSONAL'),
  (332,'in.faucibus.morbi@musaenean.co.uk','INSTITUCIONAL'),
  (169,'eget.laoreet@duifusce.co.uk','PERSONAL');
INSERT INTO mail (id_persona,mail,tipo)
VALUES
  (270,'nunc.id@rhoncusdonec.edu','EMPRESARIAL'),
  (178,'ac.fermentum.vel@tellussuspendisse.org','PERSONAL'),
  (216,'mi.ac@diamdictum.edu','INSTITUCIONAL'),
  (268,'adipiscing.enim@quisarcu.net','PERSONAL'),
  (483,'sem.ut@liberoproin.ca','PERSONAL'),
  (367,'magna.sed.eu@nulla.org','EMPRESARIAL'),
  (336,'mauris.rhoncus@consectetuereuismod.org','INSTITUCIONAL'),
  (267,'a.mi@classaptenttaciti.net','PERSONAL'),
  (137,'erat.vitae@eu.edu','PERSONAL'),
  (350,'nunc.laoreet.lectus@egestasligula.net','INSTITUCIONAL');
INSERT INTO mail (id_persona,mail,tipo)
VALUES
  (139,'lorem.eget@maurisvestibulumneque.edu','INSTITUCIONAL'),
  (349,'cursus.vestibulum@eget.com','PERSONAL'),
  (331,'odio.aliquam@accumsanconvallis.net','PERSONAL'),
  (117,'non.lobortis@sedeu.net','PERSONAL'),
  (411,'ut.nisi@dui.com','PERSONAL'),
  (349,'pellentesque.habitant@sit.org','EMPRESARIAL'),
  (499,'in.mi@lacusut.ca','INSTITUCIONAL'),
  (303,'tincidunt.dui@proinnisl.org','PERSONAL'),
  (486,'felis.orci@parturient.edu','EMPRESARIAL'),
  (328,'neque.nullam@auctorullamcorpernisl.edu','INSTITUCIONAL');
INSERT INTO mail (id_persona,mail,tipo)
VALUES
  (204,'eros.nam@euligula.ca','EMPRESARIAL'),
  (390,'gravida.sit@semutdolor.edu','INSTITUCIONAL'),
  (212,'interdum.enim@venenatisvelfaucibus.co.uk','EMPRESARIAL'),
  (175,'aliquam.arcu.aliquam@sem.edu','PERSONAL'),
  (468,'ut.lacus.nulla@est.ca','EMPRESARIAL'),
  (278,'felis@malesuadaid.co.uk','EMPRESARIAL'),
  (545,'ante.iaculis.nec@nuncuterat.edu','PERSONAL'),
  (106,'pede@nullacras.ca','EMPRESARIAL'),
  (445,'fermentum.arcu.vestibulum@lacusaliquam.net','EMPRESARIAL'),
  (360,'consectetuer@enimnonnisi.ca','INSTITUCIONAL');
INSERT INTO mail (id_persona,mail,tipo)
VALUES
  (228,'et@dolorquam.ca','EMPRESARIAL'),
  (438,'lorem.semper@nullamvitae.com','INSTITUCIONAL'),
  (279,'vehicula.pellentesque@mauris.net','INSTITUCIONAL'),
  (526,'euismod.urna@purusmauris.co.uk','EMPRESARIAL'),
  (358,'non.nisi.aenean@curabitur.net','EMPRESARIAL'),
  (528,'ut.eros.non@pede.ca','PERSONAL'),
  (104,'tristique.pharetra@facilisis.org','INSTITUCIONAL'),
  (165,'egestas.urna@egetmassa.com','EMPRESARIAL'),
  (112,'non.dui.nec@lacusquisque.com','EMPRESARIAL'),
  (348,'ornare.libero@ametrisus.com','INSTITUCIONAL');
INSERT INTO mail (id_persona,mail,tipo)
VALUES
  (591,'augue.ac@ametultricies.com','INSTITUCIONAL'),
  (345,'pellentesque.sed.dictum@ipsumacmi.co.uk','INSTITUCIONAL'),
  (577,'aliquet.phasellus@ultricesiaculis.edu','INSTITUCIONAL'),
  (282,'dui.fusce.aliquam@nullamenim.ca','EMPRESARIAL'),
  (244,'metus.in@donecfringilla.org','INSTITUCIONAL'),
  (528,'dolor.dapibus@lacusquisqueimperdiet.edu','EMPRESARIAL'),
  (394,'sit.amet@maurisid.co.uk','EMPRESARIAL'),
  (105,'ante.blandit@turpisnonenim.net','INSTITUCIONAL'),
  (311,'quam.pellentesque.habitant@mattissemper.org','INSTITUCIONAL'),
  (540,'pede.nonummy.ut@vitaesodales.co.uk','INSTITUCIONAL');
INSERT INTO mail (id_persona,mail,tipo)
VALUES
  (268,'mattis.semper@aliquamultricesiaculis.co.uk','INSTITUCIONAL'),
  (450,'vulputate.dui@suspendissetristique.net','EMPRESARIAL'),
  (108,'metus@ullamcorperduis.net','EMPRESARIAL'),
  (104,'egestas.nunc@vulputateduinec.org','PERSONAL'),
  (386,'curae.phasellus.ornare@sapienaenean.net','INSTITUCIONAL'),
  (494,'erat.semper@faucibusut.co.uk','PERSONAL'),
  (211,'non.cursus@iaculisenim.edu','PERSONAL'),
  (393,'donec.tincidunt@egetlacusmauris.co.uk','INSTITUCIONAL'),
  (101,'luctus.et.ultrices@eratvivamus.org','EMPRESARIAL'),
  (173,'nunc.ullamcorper@fuscefermentum.com','EMPRESARIAL');
INSERT INTO mail (id_persona,mail,tipo)
VALUES
  (277,'commodo.tincidunt.nibh@placeratorcilacus.net','PERSONAL'),
  (190,'mus.aenean@uttincidunt.com','PERSONAL'),
  (592,'lobortis.quam@ametluctus.edu','INSTITUCIONAL'),
  (537,'libero@mauriseu.net','PERSONAL'),
  (226,'integer.in@ligulanullam.org','INSTITUCIONAL'),
  (328,'rutrum.magna.cras@ut.com','INSTITUCIONAL'),
  (413,'diam.vel@quisquenonummy.net','EMPRESARIAL'),
  (481,'sagittis.nullam@egestasa.co.uk','EMPRESARIAL'),
  (473,'sed.dictum@egetdictum.org','PERSONAL'),
  (285,'vel.arcu.eu@atfringillapurus.co.uk','INSTITUCIONAL');
INSERT INTO mail (id_persona,mail,tipo)
VALUES
  (171,'ac.arcu.nunc@ornaresagittisfelis.co.uk','EMPRESARIAL'),
  (584,'elit@risusdonec.edu','EMPRESARIAL'),
  (458,'convallis@maurisvel.co.uk','INSTITUCIONAL'),
  (529,'dictum.proin.eget@egetlacusmauris.co.uk','PERSONAL'),
  (420,'arcu.vel@accumsan.edu','PERSONAL'),
  (369,'vestibulum@eteros.co.uk','EMPRESARIAL'),
  (580,'nibh.lacinia@massalobortis.com','EMPRESARIAL'),
  (316,'et.nunc.quisque@etiamlaoreetlibero.ca','INSTITUCIONAL'),
  (296,'tincidunt.orci@tristiquepharetraquisque.ca','EMPRESARIAL'),
  (103,'sapien@necquam.org','INSTITUCIONAL');
INSERT INTO mail (id_persona,mail,tipo)
VALUES
  (442,'nec@dolorsitamet.co.uk','PERSONAL'),
  (539,'aliquet@velit.co.uk','INSTITUCIONAL'),
  (202,'euismod.in.dolor@donecfelis.edu','INSTITUCIONAL'),
  (599,'malesuada.fames@ligula.org','INSTITUCIONAL'),
  (398,'nulla.eu@eleifendegestassed.com','EMPRESARIAL'),
  (428,'vitae@erosnec.ca','PERSONAL'),
  (177,'dis@egestaslacinia.co.uk','EMPRESARIAL'),
  (114,'euismod.est.arcu@commodo.ca','EMPRESARIAL'),
  (160,'nunc.ullamcorper@sitamet.co.uk','PERSONAL'),
  (435,'nulla.integer@bibendumfermentummetus.com','PERSONAL');
INSERT INTO mail (id_persona,mail,tipo)
VALUES
  (265,'eget.venenatis.a@craseutellus.ca','PERSONAL'),
  (194,'nunc.in.at@enimnec.edu','PERSONAL'),
  (391,'non.luctus@loremvitaeodio.edu','INSTITUCIONAL'),
  (290,'vel.turpis@gravidapraesenteu.com','INSTITUCIONAL'),
  (101,'nec@molestie.net','PERSONAL'),
  (537,'ultricies.adipiscing@lobortisultrices.co.uk','PERSONAL'),
  (119,'blandit.viverra.donec@eteros.org','INSTITUCIONAL'),
  (446,'sem@aliquet.edu','INSTITUCIONAL'),
  (332,'eleifend.vitae@gravida.org','INSTITUCIONAL'),
  (493,'sed@viverra.edu','EMPRESARIAL');
INSERT INTO mail (id_persona,mail,tipo)
VALUES
  (416,'lobortis.risus@vitae.ca','INSTITUCIONAL'),
  (245,'in.molestie@lacuspedesagittis.net','EMPRESARIAL'),
  (150,'hendrerit@in.net','INSTITUCIONAL'),
  (239,'donec.tincidunt@rutrumlorem.edu','PERSONAL'),
  (170,'magna.sed@nec.net','INSTITUCIONAL'),
  (161,'enim.nunc.ut@utaliquam.net','PERSONAL'),
  (254,'nullam.lobortis@ad.com','PERSONAL'),
  (355,'molestie@morbivehicula.ca','PERSONAL'),
  (599,'condimentum.donec.at@etpede.com','PERSONAL'),
  (504,'suspendisse.dui@semconsequat.ca','INSTITUCIONAL');
INSERT INTO mail (id_persona,mail,tipo)
VALUES
  (544,'enim.curabitur@aenean.org','PERSONAL'),
  (401,'lorem@orcilacusvestibulum.org','PERSONAL'),
  (173,'enim.condimentum.eget@congueturpisin.co.uk','PERSONAL'),
  (292,'quis@sollicitudin.co.uk','PERSONAL'),
  (369,'tincidunt@liberomauris.net','PERSONAL'),
  (475,'nunc.mauris@lectusjusto.co.uk','EMPRESARIAL'),
  (592,'lectus.rutrum.urna@et.co.uk','EMPRESARIAL'),
  (341,'vivamus.nisi@nequetellusimperdiet.org','EMPRESARIAL'),
  (401,'luctus.felis@ligula.com','EMPRESARIAL'),
  (497,'cras.dolor@idmollis.org','EMPRESARIAL');
INSERT INTO mail (id_persona,mail,tipo)
VALUES
  (310,'elit.curabitur@lorem.org','PERSONAL'),
  (548,'nec@montesnascetur.edu','EMPRESARIAL'),
  (170,'eros.proin.ultrices@laciniamattisinteger.edu','INSTITUCIONAL'),
  (408,'primis.in@orcidonec.co.uk','PERSONAL'),
  (356,'vivamus@fuscealiquet.com','PERSONAL'),
  (485,'mauris@nuncquisarcu.ca','INSTITUCIONAL'),
  (105,'nulla.aliquet@nullamfeugiat.org','EMPRESARIAL'),
  (173,'sapien@lorem.com','INSTITUCIONAL'),
  (152,'non@acmetusvitae.net','PERSONAL'),
  (143,'gravida.aliquam.tincidunt@felis.org','PERSONAL');
INSERT INTO mail (id_persona,mail,tipo)
VALUES
  (376,'id.blandit@felis.ca','EMPRESARIAL'),
  (324,'semper.erat@nullatincidunt.edu','EMPRESARIAL'),
  (382,'pellentesque.eget.dictum@nisl.edu','INSTITUCIONAL'),
  (367,'cras.sed@egestashendreritneque.org','PERSONAL'),
  (487,'egestas.urna@vellectus.net','INSTITUCIONAL'),
  (241,'eleifend.non.dapibus@mifelis.co.uk','EMPRESARIAL'),
  (353,'eget@atliberomorbi.com','EMPRESARIAL'),
  (343,'accumsan.sed@nonquampellentesque.net','INSTITUCIONAL'),
  (122,'iaculis.odio@dolor.ca','EMPRESARIAL'),
  (305,'porttitor.interdum@nunc.net','PERSONAL');
INSERT INTO mail (id_persona,mail,tipo)
VALUES
  (569,'aliquet@turpisnecmauris.org','EMPRESARIAL'),
  (496,'quis.turpis.vitae@nunccommodo.co.uk','EMPRESARIAL'),
  (365,'dapibus.ligula@nislmaecenas.edu','PERSONAL'),
  (203,'lacus.nulla@enimgravida.org','PERSONAL'),
  (469,'felis.donec@risusquis.net','EMPRESARIAL'),
  (346,'eu@lectus.com','EMPRESARIAL'),
  (583,'pellentesque.eget@ut.edu','INSTITUCIONAL'),
  (281,'nunc@ipsumdolor.org','INSTITUCIONAL'),
  (289,'morbi.vehicula.pellentesque@sitamet.net','EMPRESARIAL'),
  (251,'neque.tellus@amet.org','EMPRESARIAL');
INSERT INTO mail (id_persona,mail,tipo)
VALUES
  (481,'auctor@maecenasornare.org','INSTITUCIONAL'),
  (555,'diam@venenatisvel.org','INSTITUCIONAL'),
  (135,'duis.mi@nonenimmauris.edu','INSTITUCIONAL'),
  (102,'nec@egestasnunc.net','PERSONAL'),
  (365,'enim@nec.org','EMPRESARIAL'),
  (459,'aenean.sed@erat.ca','PERSONAL'),
  (574,'sagittis.felis@sedegetlacus.co.uk','INSTITUCIONAL'),
  (401,'nunc.lectus@nullainteger.ca','EMPRESARIAL'),
  (301,'orci.tincidunt@et.ca','EMPRESARIAL'),
  (404,'proin.non@pretiumaliquetmetus.ca','PERSONAL');
INSERT INTO mail (id_persona,mail,tipo)
VALUES
  (554,'consectetuer.cursus@amalesuada.com','INSTITUCIONAL'),
  (291,'curabitur.dictum@fuscefeugiat.com','INSTITUCIONAL'),
  (155,'nec@namporttitor.net','PERSONAL'),
  (574,'mauris.aliquam@phasellusinfelis.net','INSTITUCIONAL'),
  (137,'quam.quis.diam@nuncinat.ca','EMPRESARIAL'),
  (149,'ullamcorper.duis@utmi.ca','EMPRESARIAL'),
  (313,'odio@aeneaneget.net','EMPRESARIAL'),
  (260,'nunc@nullavulputatedui.ca','PERSONAL'),
  (532,'eget.massa@cursusvestibulummauris.net','EMPRESARIAL'),
  (206,'nec.urna@estnunclaoreet.com','INSTITUCIONAL');
INSERT INTO mail (id_persona,mail,tipo)
VALUES
  (396,'bibendum.donec.felis@litoratorquent.com','EMPRESARIAL'),
  (135,'nec.urna@adlitora.edu','PERSONAL'),
  (156,'etiam.imperdiet@vitaerisusduis.net','PERSONAL'),
  (136,'luctus.et@nisiaenean.com','PERSONAL'),
  (407,'ornare.tortor@anteipsum.com','PERSONAL'),
  (498,'id.erat.etiam@turpis.co.uk','INSTITUCIONAL'),
  (127,'aliquet.vel@etnunc.com','PERSONAL'),
  (386,'integer.sem.elit@utdolor.ca','PERSONAL'),
  (584,'est.congue@inconsequatenim.ca','EMPRESARIAL'),
  (581,'bibendum.donec@vitae.co.uk','INSTITUCIONAL');
